In [1]:
# Imports

import warnings
warnings.filterwarnings("ignore")

from pathlib import Path

import pandas as pd

pd.set_option("display.max_columns", None)

In [2]:
# Paths

PROJECT_ROOT = Path.cwd().parent

DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"

In [4]:
# Baseline Summary

# Create it directly from your earlier results.

baseline_summary = pd.DataFrame({
    "Cluster": [0,1,2,3],
    "Customers":[12140,3037,60714,17467],
    "Percentage":[13.00,3.25,65.03,18.71],
    "Business_Label":[
        "Budget Customers",
        "Premium Customers",
        "Regular Customers",
        "Dissatisfied Customers"
    ]
})

baseline_summary

   Cluster  Customers  Percentage          Business_Label
0        0      12140       13.00        Budget Customers
1        1       3037        3.25       Premium Customers
2        2      60714       65.03       Regular Customers
3        3      17467       18.71  Dissatisfied Customers

In [5]:
# Autoencoder Summary

autoencoder_summary = pd.DataFrame({
    "Cluster":[0,1,2,3],
    "Customers":[5464,63937,23380,577],
    "Percentage":[5.85,68.49,25.04,0.62],
    "Business_Label":[
        "High Value",
        "Mass Market",
        "Medium Value",
        "VIP Customers"
    ]
})

autoencoder_summary

   Cluster  Customers  Percentage Business_Label
0        0       5464        5.85     High Value
1        1      63937       68.49    Mass Market
2        2      23380       25.04   Medium Value
3        3        577        0.62  VIP Customers

In [6]:
# Side-by-Side Comparison

comparison = pd.DataFrame({

    "Aspect":[
        "Features",
        "Clustering Algorithm",
        "Number of Clusters",
        "Business Segments",
        "VIP Segment"
    ],

    "Baseline":[
        "11 Engineered",
        "K-Means",
        4,
        "General",
        "No"
    ],

    "Autoencoder":[
        "4 Latent Features",
        "K-Means",
        4,
        "More Distinct",
        "Yes"
    ]

})

comparison

                 Aspect       Baseline        Autoencoder
0              Features  11 Engineered  4 Latent Features
1  Clustering Algorithm        K-Means            K-Means
2    Number of Clusters              4                  4
3     Business Segments        General      More Distinct
4           VIP Segment             No                Yes